#!/usr/bin/env bash

alias l="ls -AlF"
alias mci="mvn clean install"
alias ec="mvn eclipse:clean eclipse:eclipse"
alias gj="ps auxwww|grep java|grep -v IntelliJ|grep -v grep"
alias rt="rm -rf target"
alias cd..="cd .."
alias adda="vim $HOME/.bashconf/aliases && source $HOME/.bashconf/aliases"
alias addf="vim $HOME/.bashconf/functions && source $HOME/.bashconf/functions"
alias adde="vim $HOME/.bashconf/exports && source $HOME/.bashconf/exports"
