#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage: $0 <repository name> <local dir>"
  exit 1
fi

echo "Import" 
git svn clone "$1" -s "$2"

echo "Post Processing"
cd "$2"
git gc

echo "Create Branches"
for b in $(git branch -r | grep -v 'tags/' | grep -v 'trunk'); do
  git checkout $b
  git checkout -b $b
done
git checkout master

echo "Create Tags"
for t in $(git branch -r | grep 'tags/' | cut -d '/' -f 2); do
  git checkout "tags/$t"
  git tag $t
done
git checkout master

echo
echo "Tag list:"
git tag
echo "Branch list:"
git branch

echo "Adding remote"
git remote add origin "ssh://tmenagh@source.dev.cim.comcast.net:8766/$2"
cp ../sirius/.git/hooks/commit-msg ./.git/hooks/

echo "Sending to server"
cd ..
scp -r $2 gerrit:~/tmp

echo "Check if all tags and branches were migrated, and if so push to GIT by executing the following:"
echo "cd tmp/$2"
echo git remote rm origin
echo "git remote add origin /srv/git/$2.git"
echo git push origin --all
echo git push origin --tag

ssh gerrit