#!/usr/bin/env bash
#
# up - a bash script that updates either a git or an svn repo.
#
# Copyright (c) 2012 Trevor Lalish-Menagh
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

NULL="/dev/null"
ENV="/usr/bin/env"
GIT="${ENV} git"
NOT_A_GIT_REPO="128" # a 128 error occurs when git is run in a dir that is not a git repo.
SVN="${ENV} svn"
NOT_AN_SVN_REPO="Skipped '.'" # When svn update is run in a dir that is not an svn repo, this is the result.

${GIT} pull --rebase 2> ${NULL}; GIT_ERROR_CODE=$?
if [ "${GIT_ERROR_CODE}" == "${NOT_A_GIT_REPO}" ]; then
    SVN_RESULT="$(${SVN} update 2> ${NULL})"
    if [ "${SVN_RESULT}" == "${NOT_AN_SVN_REPO}" ]; then
        echo "Update failed. Are you in a git or svn repo?"
    else
        echo "${SVN_RESULT}"
    fi
fi
